[phases.setup]
nixPkgs = ["nodejs_22", "corepack"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@10.17.1 --activate", "pnpm install --frozen-lockfile"]

[start]
cmd = "pnpm run start"