[build]
buildCommand = "pnpm install --frozen-lockfile && pnpm run gen && pnpm run build"

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
production = { PORT = "${{ PORT }}" }