[build]
buildCommand = "pnpm install --frozen-lockfile && pnpm run gen:css && pnpm run gen:routes && pnpm run gen:railway && pnpm run gen:gel:ci && pnpm run build"

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
production = { PORT = "${{ PORT }}" }