// GENERATED by @gel/generate v0.6.4

import type { setToTsType, TypeSet } from './typesystem'

export * from './cast'
export * from './collections'
export * from './detached'
export * from './for'
export * from './funcops'
export * from './globals'
export * from './group'
export * from './insert'
export * from './literal'
export * from './params'
export * from './path'
export * from './range'
export * from './select'
export * from './set'
export * from './toEdgeQL'
export * from './update'
export * from './with'

export type $infer<A extends TypeSet> = setToTsType<A>
